#version 450

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_buffer_reference : require
#extension GL_GOOGLE_include_directive : require

#include "structs.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 0, binding = 0, rgba8) uniform image2D u_Image;

layout(buffer_reference, scalar) readonly buffer CameraBuffer {
    vec3 front;
    vec3 right;
    vec3 up;
    vec3 position;
    float fov;
};

layout(buffer_reference, scalar) readonly buffer BufferRefs {
    CameraBuffer cameraBuffer;
};

layout (push_constant, scalar) uniform PushConstant {
    vec2 resolution;
    float aspectRatio;
    BufferRefs bufferRefs;
} pd;

#define FLT_MAX 3.402823466e+38

void main() {
    CameraBuffer camera = pd.bufferRefs.cameraBuffer;
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);

    vec2 uv = vec2(fragCoord) / pd.resolution;
    uv = uv * 2.0 - 1.0;
    uv.x *= pd.aspectRatio;

    Ray camRay;
    camRay.origin = camera.position;
    {
        float fov = radians(camera.fov);
        float halfHeight = tan(fov * 0.5);
        float halfWidth = halfHeight;
        vec2 screenCoords = uv * vec2(halfWidth, halfHeight);
        camRay.dir = normalize(camera.front + screenCoords.x * camera.right + screenCoords.y * camera.up);
    }

    const uint sphereCount = 3;
    Sphere spheres[sphereCount];
    spheres[0].center = vec3( 0.0, 0.0, 2.0);
    spheres[0].radius = 0.5;
    spheres[1].center = vec3(-2.0, 0.0, 2.0);
    spheres[1].radius = 0.5;
    spheres[2].center = vec3( 2.0, 0.0, 2.0);
    spheres[2].radius = 0.5;

    int idx = -1;
    float closestT = FLT_MAX;
    vec3 color = vec3(0.0);

    for(int i = 0; i < sphereCount; i++) {
        HitInfo hitInfo;
        if(DidRayHitSphere(camRay, spheres[i], hitInfo)) {
            if(closestT > hitInfo.t) {
                closestT = hitInfo.t;
                idx = i;
            }
        }
    }
    
    if(idx == -1) {
        color = mix(vec3(0.5, 0.7, 1.0), vec3(1.0), (uv.y + 1)/2);
    } else {
        if(idx == 0)
            color = vec3(1, 0, 0);
        else if(idx == 1)
            color = vec3(0, 1, 0);
        else if(idx == 2)
            color = vec3(0, 0, 1);
    }

    imageStore(u_Image, fragCoord, vec4(color, 1.0));
}
