#version 450

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 0, binding = 0, rgba8) uniform image2D u_Image;

layout (push_constant) uniform PushConstant {
    vec2 resolution;
} pd;

void main() {
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);

    vec2 uv = vec2(fragCoord) / pd.resolution;
    vec3 color = vec3(uv, 0.0);
    imageStore(u_Image, ivec2(gl_GlobalInvocationID.xy), vec4(color, 1.0));
}