#version 450

#extension GL_EXT_scalar_block_layout : require

#include "structs.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 0, binding = 0, rgba8) uniform image2D u_Image;

layout (push_constant, scalar) uniform PushConstant {
    vec2 resolution;
} pd;

void main() {
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);

    vec2 uv = vec2(fragCoord) / pd.resolution;
    uv = uv * 2.0 - 1.0;
    uv.x *= pd.resolution.x/pd.resolution.y;

    Ray camRay;
    camRay.origin = vec3(0, 0, -1);
    camRay.dir = normalize(vec3(uv, 1.0));

    Sphere sphere;
    sphere.center = vec3(0, 0, 2);
    sphere.radius = 0.5;

    vec3 color = vec3(0.0);
    HitInfo hitInfo;
    if(DidRayHitSphere(camRay, sphere, hitInfo)) {
        color = vec3(1, 0, 0);
    }

    imageStore(u_Image, fragCoord, vec4(color, 1.0));
}
